sudo: required

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: R+AzxEOoZzmh0tw2NYDEDkOqFIhLmlSs7fmKFEe9IiatfPN4V8HaYDiPEeEasUosAXDB327tTwoXCBPkdOG1G46mHv1eMvomgFy/KYSZ6bqKCdxDQFOzIGm3vG1b3OXQc20uOTCvNm7UGXnSpCEc77vlQdEAW8jkB10LUkrcQP6f3XvrbpVmdAKXDxYPhHYTt1JuRNsTHVKcbiKofLYUQRCPAC8swdLzZN/322IYdLUcKcwqVT51KV9W5qtN1flDscHTcx8kaVFTsR22g9IJQuh04tZPpJ5i3tKHwBJx1wImfJU9Yt4jET48lL/2M8FUFKB1bvaTWQ6/oVKaB2D5p30j5Wa8kTpAx/9nQW9WrpuzQQIc6PMzxCCC6uhMcOXR2zjCY3v6Cz7FhpNb75KpZpLNhXCVArkgc68QIsf96DQen8cYGjaj302SqVaHByETKExhVL8+BwXqaUj3TDNZDseM1PGb94cibR3mHMowHn7Ncew9ZCp9reeijXPcC666Oh6vIF0G76xJUHTz2Y9yf0xwNpiw5A3/uW0rAj5A30M2xm9/JzBi4D+6GNkPNPisS16DbQmZmoXS6UkkzbQEpiCwkiqznI1HjmS3GUamAdIHYPTnKnvC3pYlXPVKB3+3VlWQNSZdzM8BDno8M1HrMTprZU0KaPUiJ3ih3w8yWKM=

services:
  - docker

before_install:
 - docker-compose build

script:
 - docker-compose run web yarn test
